apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: svcsbot
      app.kubernetes.io/component: svcsbot
      app.kubernetes.io/instance: svcsbot
    name: svcsbot
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/noeloc/svcs-bot
      from:
        kind: DockerImage
        name: quay.io/noeloc/svcs-bot:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"svcsbot:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"svcsbot\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: svcsbot
      app.kubernetes.io/component: svcsbot
      app.kubernetes.io/instance: svcsbot
    name: svcsbot
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: svcsbot
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: svcsbot
      spec:
        containers:
        - env:
          - name: CHROMA_DB_LOCN
            value: /opt/app-root/data
          - name: OPENAI_API_KEY
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openaicreds
                key: password
          image: svcsbot:latest
          name: svcsbot
          ports:
          - containerPort: 8000
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: svcsbot
      app.kubernetes.io/component: svcsbot
      app.kubernetes.io/instance: svcsbot
    name: svcsbot
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: svcsbot
  status:
    loadBalancer: {}
kind: List
metadata: {}
